// <auto-generated />
using System;
using CargaClic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CargaClic.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CargaClic.Data.Seguridad.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("CodigoPadre")
                        .HasMaxLength(5);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Link")
                        .HasMaxLength(50);

                    b.Property<int>("Nivel");

                    b.Property<int>("Orden");

                    b.HasKey("Id");

                    b.ToTable("Paginas","Seguridad");
                });

            modelBuilder.Entity("CargaClic.Data.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Publico");

                    b.HasKey("Id");

                    b.ToTable("Roles","Seguridad");
                });

            modelBuilder.Entity("CargaClic.Data.Seguridad.RolPagina", b =>
                {
                    b.Property<int>("IdRol");

                    b.Property<int>("IdPagina");

                    b.Property<string>("permisos")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.HasKey("IdRol", "IdPagina");

                    b.HasIndex("IdPagina");

                    b.ToTable("RolesPaginas","Seguridad");
                });

            modelBuilder.Entity("CargaClic.Data.Seguridad.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("EnLinea");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CargaClic.Data.Seguridad.RolPagina", b =>
                {
                    b.HasOne("CargaClic.Data.Seguridad.Pagina", "Pagina")
                        .WithMany("RolPaginas")
                        .HasForeignKey("IdPagina")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CargaClic.Data.Seguridad.Rol", "Rol")
                        .WithMany("RolPaginas")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
